---

  known_interfaces:
    port 1:
      mac address: '0e:a5:71:4a:f8:3f'
    port 2:
      mac address: '00:50:b6:1a:d8:29'
    port 3:
      mac address: '00:50:b6:1a:d8:12'
    port 4:
      mac address: '00:50:b6:1a:d7:ac'

   
    