---

  known_interfaces:
    port 1:
      mac address: '00:50:b6:1a:d8:11'
    port 2:
      mac address: '00:50:b6:1a:d8:29'
    port 3:
      mac address: '00:50:b6:1a:d8:12'
    port 4:
      mac address: '00:50:b6:1a:d7:ac'

  broadcast: '192.168.1.1'  
    